//! Conformance tests for proto message wire-format serialization.
//!
//! Each test encodes a known message with prost::Message::encode_to_vec()
//! and compares the output byte-for-byte against the stored golden .bin file
//! in `conformance/vectors/proto/`.
//!
//! Golden files are generated by `conformance/src/bin/generate_golden.rs`.
//! Re-run the generator if a proto definition changes.

use aa_proto::assembly::{
    agent::v1::{DeregisterRequest, HeartbeatRequest, RegisterRequest, RegisterResponse},
    common::v1::{AgentId, Decision, RiskTier, Timestamp},
    policy::v1::{
        ActionContext, CheckActionRequest, CheckActionResponse, RedactInstructions, RedactRule, ToolCallContext,
    },
};
use conformance::load_golden_bin;
use prost::Message;

// ── AgentId ───────────────────────────────────────────────────────────────────

#[test]
fn agent_id_full_matches_golden() {
    let msg = AgentId {
        org_id: "acme-corp".into(),
        team_id: "platform".into(),
        agent_id: "did:key:z6Mkm5rByiqq5UNbvPFPfXtGJwdg2kD1T".into(),
    };
    assert_eq!(msg.encode_to_vec(), load_golden_bin("agent_id_full"));
}

#[test]
fn agent_id_minimal_matches_golden() {
    let msg = AgentId {
        org_id: "acme".into(),
        team_id: String::new(),
        agent_id: String::new(),
    };
    assert_eq!(msg.encode_to_vec(), load_golden_bin("agent_id_minimal"));
}

// ── CheckActionRequest ────────────────────────────────────────────────────────

#[test]
fn check_action_request_tool_call_matches_golden() {
    let msg = CheckActionRequest {
        agent_id: Some(AgentId {
            org_id: "acme-corp".into(),
            team_id: "platform".into(),
            agent_id: "did:key:z6Mkm5rByiqq5UNbvPFPfXtGJwdg2kD1T".into(),
        }),
        credential_token: "tok-abc123".into(),
        trace_id: "01HZAB1234567890ABCDEF".into(),
        span_id: "01HZAB0000000000000001".into(),
        action_type: 2, // TOOL_CALL
        context: Some(ActionContext {
            action: Some(aa_proto::assembly::policy::v1::action_context::Action::ToolCall(
                ToolCallContext {
                    tool_name: "web_search".into(),
                    tool_source: "mcp".into(),
                    args_json: b"{\"query\":\"test\"}".to_vec(),
                    target_url: "https://search.example.com".into(),
                },
            )),
        }),
    };
    assert_eq!(msg.encode_to_vec(), load_golden_bin("check_action_request_tool_call"));
}

// ── CheckActionResponse ───────────────────────────────────────────────────────

#[test]
fn check_action_response_allow_matches_golden() {
    let msg = CheckActionResponse {
        decision: Decision::Allow as i32,
        reason: "Tool 'web_search' is allowed by policy rule".into(),
        policy_rule: "rule:allow-declared-tools-v1".into(),
        approval_id: String::new(),
        redact: None,
        decision_latency_us: 312,
    };
    assert_eq!(msg.encode_to_vec(), load_golden_bin("check_action_response_allow"));
}

#[test]
fn check_action_response_redact_matches_golden() {
    let msg = CheckActionResponse {
        decision: Decision::Redact as i32,
        reason: "Credential detected in args_json".into(),
        policy_rule: "rule:redact-credentials-v1".into(),
        approval_id: String::new(),
        redact: Some(RedactInstructions {
            rules: vec![RedactRule {
                field_path: "$.args.api_key".into(),
                replacement: "[REDACTED]".into(),
            }],
        }),
        decision_latency_us: 520,
    };
    assert_eq!(msg.encode_to_vec(), load_golden_bin("check_action_response_redact"));
}

// ── RegisterRequest / RegisterResponse ───────────────────────────────────────

#[test]
fn register_request_matches_golden() {
    let msg = RegisterRequest {
        agent_id: Some(AgentId {
            org_id: "acme-corp".into(),
            team_id: "platform".into(),
            agent_id: "did:key:z6Mkm5rByiqq5UNbvPFPfXtGJwdg2kD1T".into(),
        }),
        name: "acme-platform-agent-v1".into(),
        framework: "langgraph".into(),
        version: "1.2.3".into(),
        risk_tier: RiskTier::Medium as i32,
        tool_names: vec!["web_search".into(), "code_interpreter".into()],
        public_key: "ed25519:z6MkkMh5nVgAeTf9ZLaD3ABCDE".into(),
        metadata: [
            ("env".to_string(), "production".to_string()),
            ("team".to_string(), "platform".to_string()),
        ]
        .into_iter()
        .collect(),
    };
    // RegisterRequest contains a HashMap metadata field whose serialisation order
    // is non-deterministic. Use a round-trip check instead of a golden comparison.
    let bytes = msg.encode_to_vec();
    assert!(!bytes.is_empty());
    let decoded = RegisterRequest::decode(bytes.as_slice()).expect("decode must succeed");
    assert_eq!(decoded.name, msg.name);
    assert_eq!(decoded.framework, msg.framework);
    assert_eq!(decoded.tool_names, msg.tool_names);
    assert_eq!(decoded.metadata, msg.metadata);
}

#[test]
fn register_response_matches_golden() {
    let msg = RegisterResponse {
        credential_token: "eyJhbGciOiJFZERTQSJ9.tok.sig".into(),
        assigned_policy: "policy:acme-standard-v2".into(),
        heartbeat_interval_sec: 30,
    };
    assert_eq!(msg.encode_to_vec(), load_golden_bin("register_response"));
}

// ── HeartbeatRequest ──────────────────────────────────────────────────────────

#[test]
fn heartbeat_request_matches_golden() {
    let msg = HeartbeatRequest {
        agent_id: Some(AgentId {
            org_id: "acme-corp".into(),
            team_id: "platform".into(),
            agent_id: "did:key:z6Mkm5rByiqq5UNbvPFPfXtGJwdg2kD1T".into(),
        }),
        credential_token: "tok-abc123".into(),
        active_runs: 3,
        actions_count: 17,
    };
    assert_eq!(msg.encode_to_vec(), load_golden_bin("heartbeat_request"));
}

// ── DeregisterRequest ─────────────────────────────────────────────────────────

#[test]
fn deregister_request_matches_golden() {
    let msg = DeregisterRequest {
        agent_id: Some(AgentId {
            org_id: "acme-corp".into(),
            team_id: "platform".into(),
            agent_id: "did:key:z6Mkm5rByiqq5UNbvPFPfXtGJwdg2kD1T".into(),
        }),
        credential_token: "tok-abc123".into(),
        reason: "clean shutdown".into(),
    };
    assert_eq!(msg.encode_to_vec(), load_golden_bin("deregister_request"));
}

// ── Timestamp ─────────────────────────────────────────────────────────────────

#[test]
fn timestamp_matches_golden() {
    let msg = Timestamp {
        unix_ms: 1_745_740_800_000,
    };
    assert_eq!(msg.encode_to_vec(), load_golden_bin("timestamp"));
}

// ── Decode round-trips ────────────────────────────────────────────────────────

#[test]
fn agent_id_full_round_trips() {
    let original = AgentId {
        org_id: "acme-corp".into(),
        team_id: "platform".into(),
        agent_id: "did:key:z6Mkm5rByiqq5UNbvPFPfXtGJwdg2kD1T".into(),
    };
    let bytes = original.encode_to_vec();
    let decoded = AgentId::decode(bytes.as_slice()).expect("decode AgentId");
    assert_eq!(decoded, original);
}

#[test]
fn check_action_response_allow_round_trips() {
    let golden = load_golden_bin("check_action_response_allow");
    let decoded = CheckActionResponse::decode(golden.as_slice()).expect("decode CheckActionResponse");
    assert_eq!(decoded.decision, Decision::Allow as i32);
    assert_eq!(decoded.decision_latency_us, 312);
    assert!(decoded.redact.is_none());
}
