//! AAASM-5352 — evidence that the canonical finding model changes nothing the
//! scanner observably does.
//!
//! ADR 0032 §2 allows the canonical model to wrap `CredentialKind` and forbids
//! it from replacing, renaming or renumbering it. "Nothing observable changed"
//! is a claim about output, so this file demonstrates it with output rather
//! than asserting it in prose.
//!
//! The golden beside this file was generated by running [`render_report`] —
//! character-for-character the function below — against `main` at `95dbafe7`,
//! the commit this branch is based on, *before* any of it existed. The first
//! test regenerates the report from the current tree and requires it to be
//! byte-identical. Any change to which findings are produced, where their spans
//! start, what they are labelled, or what the redacted text looks like fails it.
//!
//! Note the direction: the golden is a *baseline capture*, not a snapshot of
//! current behaviour. It records what the scanner did before this change, so
//! regenerating it to make a failure go away would destroy the only thing it is
//! for (ADR 0032 forbidden design #9, applied to a golden of our own).
//!
//! The second test closes the other half. Byte-identical scanner output would
//! also be produced by a canonical model that simply lost information, so it
//! additionally requires every finding's kind, offset and redaction label to be
//! recoverable from its canonical form alone.

use aa_security::canonical::CanonicalFinding;
use aa_security::{CredentialScanner, ScanResult};

/// A corpus spanning every detector family the built-in scanner has, plus the
/// two payload shapes that have historically broken it: mixed `zh-TW`/English
/// text (AAASM-5344) and text with no secret in it at all.
const CORPUS: &[(&str, &str)] = &[
    ("anthropic", "auth header: sk-ant-api03-Zm9vYmFyYmF6cXV1eDEyMzQ1Njc4OTA gets sent"),
    ("openai", "OPENAI_API_KEY=sk-proj-abcdefghijklmnopqrstuvwxyz012345\nexport it"),
    ("aws_long_term", "aws_access_key_id = AKIAIOSFODNN7EXAMPLE"),
    ("aws_sts", "temporary creds: ASIAY34FZKBOKMUTVV7A"),
    ("gcp", "{\"type\": \"service_account\", \"project_id\": \"demo-1\"}"),
    ("gcp_compact", "{\"type\":\"service_account\",\"project_id\":\"demo-2\"}"),
    (
        "azure",
        "DefaultEndpointsProtocol=https;AccountName=acct;AccountKey=Zm9vYmFyYmF6cXV1eDEyMzQ1Njc4OTA=;",
    ),
    ("github_pat_classic", "token ghp_16C7e42F292c6912E7710c838347Ae178B4a"),
    ("github_pat_fine", "token github_pat_11ABCDEFG0abcdefghijkl_ZZZZZZZZZZZZZZZZZZZZZZ"),
    ("github_app", "installation ghs_16C7e42F292c6912E7710c838347Ae178B4a"),
    ("github_oauth", "oauth gho_16C7e42F292c6912E7710c838347Ae178B4a"),
    ("github_user", "user ghu_16C7e42F292c6912E7710c838347Ae178B4a"),
    ("github_refresh", "refresh ghr_16C7e42F292c6912E7710c838347Ae178B4a"),
    ("slack_bot", "SLACK=xoxb-AbCdEf"),
    ("slack_user", "SLACK=xoxp-AbCdEf"),
    ("slack_oauth", "SLACK=xoxa-AbCdEf"),
    ("slack_refresh", "SLACK=xoxr-AbCdEf"),
    ("slack_app", "SLACK=xapp-AbCdEf"),
    ("postgres", "DATABASE_URL=postgres://svc:hunter2@db.internal:5432/app"),
    ("mysql", "DATABASE_URL=mysql://svc:hunter2@db.internal:3306/app"),
    ("mongodb", "DATABASE_URL=mongodb://svc:hunter2@db.internal:27017/app"),
    (
        "pem_rsa",
        "-----BEGIN RSA PRIVATE KEY-----\nMIIEowIBAAKCAQEAxGZ1bGxvZmVudHJvcHlkYXRhaGVyZTEyMzQ1Njc4OTBhYmNk\n-----END RSA PRIVATE KEY-----",
    ),
    (
        "pem_ec",
        "-----BEGIN EC PRIVATE KEY-----\nMHcCAQEEIJ1bGxvZmVudHJvcHlkYXRhaGVyZTEyMzQ1Njc4OTBhYmNkZWZnaGlq\n-----END EC PRIVATE KEY-----",
    ),
    (
        "pem_openssh",
        "-----BEGIN OPENSSH PRIVATE KEY-----\nb3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtz\n-----END OPENSSH PRIVATE KEY-----",
    ),
    (
        "pem_pkcs8",
        "-----BEGIN PRIVATE KEY-----\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDGZ1bGxvZmVu\n-----END PRIVATE KEY-----",
    ),
    (
        "pem_pgp",
        "-----BEGIN PGP PRIVATE KEY BLOCK-----\nlQOYBGF1bGxvZmVudHJvcHlkYXRhaGVyZTEyMzQ1Njc4OTBhYmNkZWZnaGlqa2xt\n-----END PGP PRIVATE KEY BLOCK-----",
    ),
    ("credit_card", "card on file 4111111111111111 expires soon"),
    ("email", "contact alice.smith@example.com for access"),
    ("ssn", "employee record 123-45-6789 filed"),
    ("high_entropy_b64", "opaque=Zm9vYmFyYmF6cXV1eDEyMzQ1Njc4OTBhYmNkZWY="),
    (
        "high_entropy_hex",
        "digest=3f786850e387550fdab836ed7e6dc881de23001b3f786850e387550fdab836ed",
    ),
    (
        "mixed_zh_tw_clean",
        "使用者詢問：請幫我把這份報告翻譯成英文，並整理成三個重點。The agent replied with a summary of the quarterly results and asked whether the customer wanted the appendix included as well. 助理回覆：好的，我會在明天下午之前完成。",
    ),
    (
        "mixed_zh_tw_with_secret",
        "設定檔內容如下，請協助檢查：DATABASE_URL=postgres://svc:hunter2@db.internal:5432/app 以及 API 金鑰 sk-ant-api03-Zm9vYmFyYmF6cXV1eDEyMzQ1Njc4OTA，謝謝。",
    ),
    (
        "clean_prose",
        "The deployment finished at noon and the rollout looks healthy across all three regions.",
    ),
    (
        "overlapping_url_and_email",
        "connect via postgres://alice@example.com:hunter2@db.internal:5432/app now",
    ),
];

/// Render the scanner's complete observable output for the corpus.
///
/// Uses only the scanner's public API — kind label, byte offset, redaction label
/// and the redacted text — so this function is compilable against any revision
/// and the report it produces is directly comparable across revisions.
fn render_report() -> String {
    let scanner = CredentialScanner::new();
    let mut out = String::new();
    for (name, text) in CORPUS {
        let result = scanner.scan(text);
        out.push_str(&format!("## {name}\n"));
        out.push_str(&format!("findings: {}\n", result.findings.len()));
        for f in &result.findings {
            out.push_str(&format!("  {} @{} {}\n", f.kind.as_str(), f.offset, f.matched));
        }
        out.push_str(&format!("redacted: {}\n", result.redact(text).replace('\n', "\\n")));
    }
    out
}

/// The scanner's observable output has not moved since `main` at `95dbafe7`.
#[test]
fn scanner_output_is_byte_identical_to_the_pre_canonical_baseline() {
    let expected = include_str!("canonical_no_behaviour_change.golden");
    assert_eq!(
        render_report(),
        expected,
        "scanner output diverged from the baseline captured before the canonical model existed"
    );
}

/// Everything the scanner reports survives the trip through the canonical model.
///
/// Kind, offset and label are each recovered from the canonical finding and
/// compared against the scanner finding they came from, so the projection is
/// shown to be lossless over real scanner output — not just over the synthetic
/// `CredentialKind` enumeration the round-trip unit test covers.
#[test]
fn every_scanner_finding_is_recoverable_from_its_canonical_form() {
    let scanner = CredentialScanner::new();
    let mut checked = 0usize;

    for (name, text) in CORPUS {
        let result: ScanResult = scanner.scan(text);
        for finding in &result.findings {
            let canonical = CanonicalFinding::try_from(finding).expect("every scanner finding has a well-formed span");

            assert_eq!(
                canonical.category.to_credential_kind().as_ref(),
                Some(&finding.kind),
                "{name}: {} did not survive the canonical projection",
                finding.kind.as_str()
            );
            assert_eq!(
                canonical.span.start(),
                finding.offset,
                "{name}: span start moved for {}",
                finding.kind.as_str()
            );
            assert_eq!(
                canonical.category.redaction_label(),
                finding.matched,
                "{name}: redaction label changed for {}",
                finding.kind.as_str()
            );
            checked += 1;
        }
    }

    // A corpus that stopped producing findings would pass every assertion above
    // while proving nothing.
    assert!(
        checked >= 40,
        "expected the corpus to exercise many findings, saw {checked}"
    );
}
