//! AAASM-5903 — the sensitive-data reference journey, fully out-of-process.
//!
//! `e2e_proxy_redaction_telemetry.rs` (AAASM-5871) proves the same chain
//! in-process: a real `aa_proxy::proxy::ProxyServer` and a real
//! `aa_api::server::serve_telemetry_grpc` call, both constructed directly by
//! the test. That is deliberate and stays as a fast library-level test — but
//! it hand-wires the two production wiring steps a release-blocking journey
//! is supposed to prove (nothing launches `aa-proxy` or `aa-api-server` as a
//! process, so a defect in how `aasm proxy start` or the shipped
//! `aa-api-server` binary actually assembles those pieces would not be
//! caught here). This file is the registry's evidence selector instead: a
//! real `aa-proxy` OS process (via `TrustedProxy::start_intercepting`,
//! AAASM-5902) and the real shipped `aa-api-server` binary
//! (`ApiServerProcess`, AAASM-5902), talking over the genuine loopback gRPC
//! telemetry hop and the genuine `/api/v1/alerts` HTTP surface.
//!
//! Four tests:
//!
//! 1. [`full_chain_redaction_reaches_operator_visible_api`] — the positive
//!    case: a canary reaches the proxy over a real HTTPS request, is
//!    redacted before forwarding, and the resulting alert is observable on
//!    the live `aa-api-server`'s REST surface. Asserts the raw canary is
//!    absent from every non-browser destination it could otherwise leak
//!    into, plus positive evidence that redaction and the telemetry hop
//!    both actually fired, plus real cross-process `event_id` correlation
//!    between the two processes' own logs.
//! 2. [`unreachable_telemetry_ingest_is_reported_unmeasured_not_a_measured_zero`]
//!    — the same harness with the telemetry endpoint pointed at a closed
//!    port. `/api/v1/alerts` reports zero regardless of whether a
//!    detection genuinely happened; this test proves that zero must never
//!    be read as "no incident" on its own — the proxy's own log carries
//!    independent evidence that a finding occurred and the best-effort
//!    report failed, which is the fact a reader who only checked the API
//!    would otherwise miss.
//! 3. [`alert_only_forwards_the_canary_and_produces_no_alert`] — the genuine
//!    negative control the security-lane registry rule (AAASM-5877) requires
//!    for whichever journey row cites this test as evidence: same harness,
//!    `AA_PROXY_CREDENTIAL_ACTION=alert_only`, asserting the *opposite*
//!    outcome test 1 asserts (raw canary reaches upstream, no dashboard
//!    alert) — proving test 1's assertions are load-bearing rather than
//!    vacuously true regardless of what the proxy actually does.
//! 4. [`e2e_fixture_main`] (`#[ignore]`) — a long-running fixture entry
//!    point, modeled on `e2e_hitl_approval.rs`'s pattern, for AAASM-5904's
//!    Playwright spec to spawn. Sends the same canary request test 1 does
//!    before printing READY, so the alert already exists by the time the
//!    browser spec navigates to it — all orchestration stays in Rust.
//!
//! # Why the proxy audit JSONL destination needs an extra env var here
//!
//! `aa-integration-tests/examples/proxy_with_mock_upstream.rs` builds its
//! `ProxyServer` via the bare `ProxyServer::new` constructor (audit sink
//! `None`) — nothing in that example previously wired
//! `AA_PROXY_AUDIT_JSONL_PATH` the way `aa_proxy::run()` does, so a journey
//! that wants "the raw canary is absent from the proxy's own audit JSONL" as
//! a genuine forbidden-destination check had no audit file to check at all.
//! Fixed here (test-only code, not the production `aa-proxy` binary) by
//! mirroring `aa_proxy::run()`'s own audit-sink construction in the example,
//! gated on the same `AA_PROXY_AUDIT_JSONL_PATH` env var production reads.
//!
//! # Synthetic secret only
//!
//! Every canary here is generated by [`common::canary::Canary`], unique per
//! process run — never a real credential.

mod common;
mod proxy_trust_support;

use std::io::Read;
use std::net::SocketAddr;
use std::path::Path;
use std::time::Duration;

use base64::Engine as _;
use rustls::pki_types::{CertificateDer, ServerName};
use rustls::{ClientConfig, RootCertStore};
use tokio::io::{AsyncBufReadExt, AsyncReadExt as _, AsyncWriteExt as _, BufReader};
use tokio::net::TcpStream;
use tokio_rustls::TlsConnector;

use aa_proxy::tls::CaStore;
use aa_security::CredentialKind;

use common::api_server::ApiServerProcess;
use common::canary::Canary;
use common::capturing_upstream::{CapturingUpstream, UpstreamOptions};
use proxy_trust_support::TrustedProxy;

/// LLM hostname the client CONNECTs to; classified by the proxy's own host
/// detection as an LLM endpoint, which is what routes the request into the
/// MitM + body-inspection + redaction branch rather than a transparent tunnel.
const LLM_HOSTNAME: &str = "api.anthropic.com";

fn install_crypto_provider() {
    use std::sync::Once;
    static INIT: Once = Once::new();
    INIT.call_once(|| {
        let _ = rustls::crypto::ring::default_provider().install_default();
    });
}

/// Build a [`ClientConfig`] that trusts `ca_dir`'s root CA — the same CA the
/// proxy issues its MitM leaves from, since `TrustedProxy::start_intercepting`
/// and this harness's [`CapturingUpstream`] share one `ca_dir`.
async fn client_trust_proxy_ca(ca_dir: &Path) -> anyhow::Result<ClientConfig> {
    let pem = tokio::fs::read_to_string(ca_dir.join("ca-cert.pem")).await?;
    let body: String = pem.lines().filter(|l| !l.starts_with("-----")).collect();
    let der_bytes = base64::engine::general_purpose::STANDARD.decode(body)?;
    let mut roots = RootCertStore::empty();
    roots.add(CertificateDer::from(der_bytes))?;
    Ok(ClientConfig::builder()
        .with_root_certificates(roots)
        .with_no_client_auth())
}

/// Drive one real HTTPS request carrying `body` through `proxy_addr` to
/// [`LLM_HOSTNAME`], returning the CONNECT status line so a caller can assert
/// the tunnel itself succeeded.
async fn send_through_proxy(
    proxy_addr: SocketAddr,
    client_config: std::sync::Arc<ClientConfig>,
    body: &str,
) -> anyhow::Result<String> {
    let tcp = TcpStream::connect(proxy_addr).await?;
    let target = format!("{LLM_HOSTNAME}:443");
    let connect = format!("CONNECT {target} HTTP/1.1\r\nHost: {target}\r\n\r\n");
    let mut tcp = tcp;
    tcp.write_all(connect.as_bytes()).await?;

    let mut reader = BufReader::new(tcp);
    let mut status_line = String::new();
    reader.read_line(&mut status_line).await?;
    loop {
        let mut h = String::new();
        reader.read_line(&mut h).await?;
        if h.trim().is_empty() {
            break;
        }
    }
    anyhow::ensure!(
        status_line.contains("200"),
        "CONNECT must succeed for a redact/alert-only credential action, got: {status_line}"
    );

    let server_name = ServerName::try_from(LLM_HOSTNAME.to_string())?;
    let connector = TlsConnector::from(client_config);
    let tcp = reader.into_inner();
    let mut tls = connector.connect(server_name, tcp).await?;

    let req = format!(
        "POST /v1/messages HTTP/1.1\r\nHost: {LLM_HOSTNAME}\r\nContent-Type: application/json\r\nContent-Length: {}\r\n\r\n{}",
        body.len(),
        body,
    );
    tls.write_all(req.as_bytes()).await?;
    let mut response_buf = vec![0u8; 1024];
    let _ = tokio::time::timeout(Duration::from_secs(2), tls.read(&mut response_buf)).await;
    Ok(status_line)
}

/// Everything one journey run needs, torn down together at the end of the
/// calling test via each field's own `Drop`.
struct Journey {
    api: ApiServerProcess,
    proxy: TrustedProxy,
    upstream: CapturingUpstream,
    canary: Canary,
    #[allow(dead_code)] // keeps the CA + audit-jsonl temp dirs alive for the test's duration
    tmp: tempfile::TempDir,
    audit_jsonl_path: std::path::PathBuf,
}

/// Stand up the full out-of-process chain: a real `aa-api-server`, a real
/// `aa-proxy` (via the sanctioned `proxy_with_mock_upstream` example) pointed
/// at a real TLS-capturing upstream, sharing one CA and one canary.
///
/// `credential_action` is one of `redact_only` | `alert_only` (never `block` —
/// this journey's claim is about what gets forwarded and reported, which a
/// block decision short-circuits entirely). `telemetry_endpoint_override`
/// lets test 2 point the proxy's telemetry client at an address nothing is
/// listening on, instead of the real `aa-api-server`'s telemetry ingest.
async fn spawn_journey(credential_action: &str, telemetry_endpoint_override: Option<&str>) -> anyhow::Result<Journey> {
    install_crypto_provider();

    // AAASM-5903 finding: the shipped `aa-api-server` (`aa_api::serve_local` →
    // `run_server_with_spa`) wraps its ENTIRE serve loop in
    // `tokio::time::timeout(DRAIN_TIMEOUT, serve)` (`aa-api/src/server.rs`) —
    // not just the drain phase after a shutdown signal, the whole lifetime —
    // so every real deployment self-terminates ~30s after start regardless of
    // traffic. Filed as AAASM-5908 (production defect, out of this Subtask's
    // "no product code changes" scope). Worked around here, not fixed there:
    // `ApiServerProcess` is spawned LAST, after every slow step (building and
    // starting the real `aa-proxy` via `aasm proxy start`) is already done, so
    // its 30s clock only starts ticking moments before the one real request
    // this journey sends. The telemetry port is picked before that so the
    // proxy's `AA_PROXY_TELEMETRY_ENDPOINT` env is known without api needing
    // to be alive yet.
    let telemetry_port = match telemetry_endpoint_override {
        Some(_) => None, // unused when an explicit override is supplied
        None => Some(common::managed_process::pick_free_port()?),
    };
    let telemetry_endpoint = match telemetry_endpoint_override {
        Some(addr) => format!("http://{addr}"),
        None => format!("http://127.0.0.1:{}", telemetry_port.expect("computed above")),
    };

    let tmp = tempfile::tempdir()?;
    let ca_dir = tmp.path().join("ca");
    std::fs::create_dir_all(&ca_dir)?;
    let ca = CaStore::load_or_create(&ca_dir).await?;

    let canary = Canary::new(CredentialKind::AnthropicKey);
    let upstream = CapturingUpstream::start_tls(
        &ca,
        UpstreamOptions {
            hostname: LLM_HOSTNAME.to_owned(),
            ..Default::default()
        },
    )
    .await?;

    let state_dir = tmp.path().join("state");
    std::fs::create_dir_all(&state_dir)?;
    let audit_jsonl_path = tmp.path().join("proxy-audit.jsonl");

    let extra_env = [
        ("AA_PROXY_TELEMETRY_ENDPOINT", telemetry_endpoint.as_str()),
        ("AA_PROXY_CREDENTIAL_ACTION", credential_action),
        (
            "AA_PROXY_AUDIT_JSONL_PATH",
            audit_jsonl_path.to_str().expect("temp path is utf-8"),
        ),
        // The proxy logs `event_id` at `debug` level when it reports
        // redaction telemetry (aa-proxy/src/proxy/mod.rs); without this,
        // `EnvFilter::from_default_env()`'s empty default shows nothing and
        // cross-process log correlation would have nothing to correlate.
        ("RUST_LOG", "aa_proxy=debug,info"),
    ];
    let proxy = TrustedProxy::start_intercepting(&ca_dir, upstream.addr, &state_dir, &extra_env)?;

    // Spawned last — see the module-level note above on why.
    let api = ApiServerProcess::spawn_with(telemetry_port, Duration::from_secs(30))?;

    Ok(Journey {
        api,
        proxy,
        upstream,
        canary,
        tmp,
        audit_jsonl_path,
    })
}

/// Poll the real `aa-api-server`'s `/api/v1/alerts` until at least one item
/// with `category == "secret_detected"` appears, or `within` expires.
/// Returns the full parsed JSON body either way so the caller asserts on it
/// rather than the poll hanging silently.
/// Result of [`wait_for_secret_alert`]: the last-observed alerts JSON, and
/// whether the api-server was ever actually reached.
///
/// `observed = false` means every poll failed (connection refused, non-2xx,
/// unparseable body) — `json` in that case is a synthesized empty shell, not
/// a real "the server answered and reported zero" response. A caller that
/// asserts absence of an alert on `json` alone without checking `observed`
/// cannot distinguish "genuinely no alert" from "the server was never
/// reachable" — exactly the false-negative-control hazard AAASM-5908 (the
/// api-server's unconditional ~30s self-terminate) makes real here, not
/// hypothetical.
struct AlertPoll {
    json: serde_json::Value,
    observed: bool,
}

async fn wait_for_secret_alert(api: &ApiServerProcess, within: Duration) -> AlertPoll {
    let url = format!("{}/api/v1/alerts", api.base_url());
    let http = reqwest::Client::new();
    let deadline = tokio::time::Instant::now() + within;
    let mut last_observed: Option<serde_json::Value> = None;
    loop {
        if let Ok(resp) = http.get(&url).send().await {
            if let Ok(json) = resp.json::<serde_json::Value>().await {
                let has_secret = json["items"]
                    .as_array()
                    .map(|items| items.iter().any(|a| a["category"] == "secret_detected"))
                    .unwrap_or(false);
                if has_secret {
                    return AlertPoll { json, observed: true };
                }
                last_observed = Some(json);
            }
        }
        if tokio::time::Instant::now() >= deadline {
            return match last_observed {
                Some(json) => AlertPoll { json, observed: true },
                None => AlertPoll {
                    json: serde_json::json!({"items": [], "total": 0}),
                    observed: false,
                },
            };
        }
        tokio::time::sleep(Duration::from_millis(50)).await;
    }
}

fn read_file(path: &std::path::Path) -> String {
    let mut s = String::new();
    if let Ok(mut f) = std::fs::File::open(path) {
        let _ = f.read_to_string(&mut s);
    }
    s
}

/// Strip ANSI SGR escape sequences (`\x1b[...m`).
///
/// `aasm proxy start --log-file` redirects the child's stdout to a plain
/// file, but the child still observes a terminal-like fd at the point its
/// `tracing_subscriber::fmt()` layer decides whether to colorize (this
/// harness measured it doing so), so the captured log carries real ANSI
/// codes wrapping each field (e.g. `event_id`, then `\x1b[2m`, then `=`,
/// then `\x1b[0m`, then the value), which silently breaks any literal
/// `"event_id="` substring search. Stripped once at parse time rather than
/// chasing the color decision through `aa-cli`/`aa-proxy` production code,
/// which is out of this Subtask's scope.
fn strip_ansi(s: &str) -> String {
    let bytes = s.as_bytes();
    let mut out = String::with_capacity(s.len());
    let mut i = 0;
    while i < bytes.len() {
        if bytes[i] == 0x1b && bytes.get(i + 1) == Some(&b'[') {
            i += 2;
            while i < bytes.len() && bytes[i] != b'm' {
                i += 1;
            }
            i += 1; // skip the terminating 'm'
            continue;
        }
        // Safe: we only ever skip whole ANSI escape byte runs, which are
        // themselves pure ASCII, so every remaining byte still starts a
        // valid UTF-8 char boundary from the original string.
        let ch_len = s[i..].chars().next().map(char::len_utf8).unwrap_or(1);
        out.push_str(&s[i..i + ch_len]);
        i += ch_len;
    }
    out
}

/// Extract the `event_id` a proxy log line of the form
/// `... event_id=<uuid> ... reported redaction telemetry to aa-api` names, if
/// present.
fn extract_reported_event_id(proxy_log: &str) -> Option<String> {
    let clean = strip_ansi(proxy_log);
    clean
        .lines()
        .find(|l| l.contains("reported redaction telemetry to aa-api"))
        .and_then(|l| l.split("event_id=").nth(1))
        .map(|rest| {
            rest.split_whitespace()
                .next()
                .unwrap_or("")
                .trim_matches('"')
                .to_owned()
        })
        .filter(|s| !s.is_empty())
}

#[tokio::test(flavor = "multi_thread")]
async fn full_chain_redaction_reaches_operator_visible_api() {
    let journey = spawn_journey("redact_only", None)
        .await
        .expect("journey harness starts");

    let body = format!(
        r#"{{"model":"claude-sonnet-4-5","messages":[{{"role":"user","content":"my key is {}"}}]}}"#,
        journey.canary.value()
    );
    let status = send_through_proxy(
        journey.proxy.addr().parse().expect("proxy addr is a socket address"),
        std::sync::Arc::new(
            client_trust_proxy_ca(journey.tmp.path().join("ca").as_path())
                .await
                .expect("client trusts proxy ca"),
        ),
        &body,
    )
    .await
    .expect("request through proxy");
    assert!(status.contains("200"), "CONNECT must succeed, got: {status}");

    // ── Destination 1: forwarded bytes — enforcement did not regress ──────
    let forwarded = journey.upstream.wait_for_requests(1, Duration::from_secs(5)).await;
    assert_eq!(forwarded, 1, "upstream must receive exactly one forwarded request");
    let forwarded_body = journey.upstream.last_body().expect("upstream captured a body");
    // Checked before the marker assertion below: if redaction genuinely
    // failed, the raw canary would be present in `forwarded_body` — running
    // the leak-safe check first means that failure panics via
    // `assert_absent`'s redacted message, not by interpolating the raw body
    // into the marker assertion's panic message.
    journey
        .canary
        .assert_absent("forwarded upstream bytes", &forwarded_body);
    assert!(
        forwarded_body.contains(&journey.canary.expected_redaction_marker()),
        "forwarded body must carry the redaction marker; got: {forwarded_body}",
    );

    // ── Destination 2: the dashboard API — positive evidence + absence ────
    let poll = wait_for_secret_alert(&journey.api, Duration::from_secs(10)).await;
    assert!(
        poll.observed,
        "the live aa-api-server's /api/v1/alerts was never successfully reached within the \
         poll window — cannot tell 'no alert' from 'server unreachable' (see AAASM-5908); \
         api log:\n{}",
        journey.api.logs(),
    );
    let alerts = poll.json;
    let items = alerts["items"].as_array().expect("items array");
    let secret = items
        .iter()
        .find(|a| a["category"] == "secret_detected")
        .unwrap_or_else(|| {
            panic!(
                "a secret_detected alert must be present on the live aa-api-server; alerts={alerts}\n\
             --- proxy log ---\n{}\n--- api log ---\n{}",
                read_file(journey.proxy.log_path()),
                journey.api.logs(),
            )
        });
    assert_eq!(secret["severity"], "critical");
    assert_eq!(secret["detected_pattern_type"], "AnthropicKey");
    let raw_alerts = serde_json::to_string(&alerts).expect("serialize alerts json");
    journey
        .canary
        .assert_absent("dashboard /api/v1/alerts response", &raw_alerts);

    // ── Destination 3: the proxy's own audit JSONL ─────────────────────────
    // Best-effort persistence, so poll briefly rather than asserting the
    // instant the request returns.
    let mut audit_content = String::new();
    for _ in 0..50 {
        audit_content = read_file(&journey.audit_jsonl_path);
        if !audit_content.is_empty() {
            break;
        }
        tokio::time::sleep(Duration::from_millis(50)).await;
    }
    assert!(
        !audit_content.is_empty(),
        "proxy audit JSONL at {} must contain at least one record",
        journey.audit_jsonl_path.display()
    );
    // Leak-safe check first — see the equivalent note on the forwarded-bytes
    // check above.
    journey.canary.assert_absent("proxy audit JSONL", &audit_content);
    assert!(
        audit_content.contains("ForwardedRedacted") || audit_content.contains("forwarded_redacted"),
        "audit JSONL must record the ForwardedRedacted decision; got: {audit_content}",
    );

    // ── Destinations 4 and 5 + cross-process event_id correlation, via logs
    //     only (AAASM-5905: event_id is dropped before reaching the alert
    //     store, so this is not reachable through the API — it is the fact
    //     this journey exists partly to make visible) ──────────────────────
    //
    // Nothing orders either log line against the alert Destination 2 observed.
    // `emit_redaction_telemetry` (aa-proxy/src/proxy/mod.rs) reports on a
    // *detached* `tokio::spawn` task and logs the `event_id` only after the RPC
    // resolves. On the aa-api side (aa-api/src/redaction_telemetry.rs) the
    // ingest line is logged and the alert republished onto the in-process
    // channel, and only then is the response sent — while the alert reaches the
    // store Destination 2 reads from in a *separate* capture task. So the two
    // lines this section needs and the alert it already saw all fan out from
    // one point:
    //
    //     api logs ingest line → alert republished ─┬→ response → proxy logs event_id
    //                                              └→ capture task → alert visible
    //
    // The two branches race, so observing the alert says nothing about whether
    // the proxy has logged yet; and the api line, though earlier in program
    // order than both, still has to reach this process's captured output.
    // Reading either log once and requiring the line to be present is therefore
    // a race, which is what AAASM-5934 recorded after it reddened four unrelated
    // Dependabot PRs. Poll for the correlated pair, re-reading both logs each
    // iteration because they grow after this point.
    //
    // Bounded by a deadline rather than an iteration count: each iteration does
    // two file reads and a sleep, so `for _ in 0..200` bounds the iterations and
    // not the time, and what needs bounding here is the wait.
    // The loop yields the observations it stopped on, rather than writing them
    // into variables declared before it: with `loop` the compiler can prove a
    // placeholder initializer is never read, and a placeholder that is never
    // read is one the assertions below could accidentally run against.
    enum Correlation {
        Converged,
        ReportFailed,
        TimedOut,
    }
    let deadline = tokio::time::Instant::now() + Duration::from_secs(10);
    let (proxy_log, api_log, correlation) = loop {
        let proxy_log = read_file(journey.proxy.log_path());
        let api_log = journey.api.logs();
        if let Some(id) = extract_reported_event_id(&proxy_log) {
            if strip_ansi(&api_log).contains(&id) {
                break (proxy_log, api_log, Correlation::Converged);
            }
        }
        // The proxy logs a *failed* report with the same `event_id` but a
        // different message, and `extract_reported_event_id` matches only the
        // success one. Waiting the window out would then end in "the proxy never
        // named an event_id" — true, and useless: the report was attempted and
        // rejected, so no later iteration can change the outcome.
        if strip_ansi(&proxy_log).contains("redaction telemetry report failed") {
            break (proxy_log, api_log, Correlation::ReportFailed);
        }
        if tokio::time::Instant::now() >= deadline {
            break (proxy_log, api_log, Correlation::TimedOut);
        }
        tokio::time::sleep(Duration::from_millis(50)).await;
    };

    // Leak-safe checks first — see the equivalent note on the forwarded-bytes
    // check above. Run on the last observed contents whether or not the
    // correlation converged, so a canary leak is reported as a leak rather
    // than being masked by the correlation panic below.
    journey.canary.assert_absent("proxy log file", &proxy_log);
    journey.canary.assert_absent("api-server log", &api_log);

    // Distinguish the three ways this can end without a correlated pair. They
    // send the next reader to different places: the proxy's RPC failing is an
    // aa-api reachability problem, no event_id at all is a proxy-side one, and
    // an id the api-server never echoed means the two processes' evidence
    // cannot be joined even though both sides reported.
    match correlation {
        Correlation::Converged => {}
        Correlation::ReportFailed => panic!(
            "the proxy's telemetry report RPC failed, so no event_id was ever accepted \
             for aa-api to echo; proxy log:\n{}",
            strip_ansi(&proxy_log)
        ),
        Correlation::TimedOut => match extract_reported_event_id(&proxy_log) {
            None => panic!(
                "proxy log must name the event_id it reported to aa-api's telemetry ingest, \
                 within the poll window; full log:\n{proxy_log}"
            ),
            Some(id) => panic!(
                "the event_id the proxy reported ({id}) must also appear in the api-server's \
                 own ingest log — otherwise the two processes' evidence cannot be correlated \
                 back to the same redaction event; api log:\n{}",
                strip_ansi(&api_log)
            ),
        },
    }
}

#[tokio::test(flavor = "multi_thread")]
async fn unreachable_telemetry_ingest_is_reported_unmeasured_not_a_measured_zero() {
    // A loopback port nothing is listening on: `connect_lazy` never fails at
    // construction, so the proxy starts normally and only the report RPC
    // itself fails, best-effort, exactly as it would against a genuinely
    // down ingest in production.
    let dead_port = {
        let l = std::net::TcpListener::bind("127.0.0.1:0").expect("bind to find a free port");
        l.local_addr().expect("local_addr").port()
    };
    // Dropping the listener frees the port; nothing rebinds it, so the
    // proxy's report RPC will hit connection-refused.
    let dead_addr = format!("127.0.0.1:{dead_port}");

    let journey = spawn_journey("redact_only", Some(&dead_addr))
        .await
        .expect("journey harness starts even with an unreachable telemetry endpoint");

    let body = format!(
        r#"{{"model":"claude-sonnet-4-5","messages":[{{"role":"user","content":"my key is {}"}}]}}"#,
        journey.canary.value()
    );
    send_through_proxy(
        journey.proxy.addr().parse().expect("proxy addr is a socket address"),
        std::sync::Arc::new(
            client_trust_proxy_ca(journey.tmp.path().join("ca").as_path())
                .await
                .expect("client trusts proxy ca"),
        ),
        &body,
    )
    .await
    .expect("request through proxy — enforcement must not depend on telemetry reachability");

    // Enforcement is unaffected: the finding still gets redacted before
    // forwarding, regardless of whether the best-effort telemetry report
    // could land anywhere.
    journey.upstream.wait_for_requests(1, Duration::from_secs(5)).await;
    let forwarded_body = journey.upstream.last_body().expect("upstream captured a body");
    assert!(
        forwarded_body.contains(&journey.canary.expected_redaction_marker()),
        "redaction must still happen even when telemetry is unreachable; got: {forwarded_body}",
    );

    // THE ASSERTION THIS TEST EXISTS FOR: the dashboard API reports zero —
    // and on its own that zero is indistinguishable from "nothing happened".
    let poll = wait_for_secret_alert(&journey.api, Duration::from_secs(3)).await;
    // `poll.observed` must be checked first: an unreachable api-server (e.g.
    // AAASM-5908's ~30s self-terminate) would make wait_for_secret_alert's
    // synthesized empty fallback indistinguishable from a genuine "server
    // answered, zero alerts" response — silently turning this into the exact
    // false pass the test exists to rule out.
    assert!(
        poll.observed,
        "the live aa-api-server was never successfully reached — cannot conclude 'no alert \
         reached it' from a server that was never actually asked; api log:\n{}",
        journey.api.logs(),
    );
    let has_secret = poll.json["items"]
        .as_array()
        .map(|items| items.iter().any(|a| a["category"] == "secret_detected"))
        .unwrap_or(false);
    assert!(
        !has_secret,
        "with the telemetry ingest unreachable, no alert can have reached the dashboard API"
    );

    // The proxy's OWN log is the independent evidence that a finding really
    // did occur and the best-effort report genuinely failed — this is what
    // distinguishes "a real 0-alert incident went unmeasured" from "there
    // was nothing to measure". A journey (or a human) that only checked the
    // dashboard API would misclassify this run as a clean pass.
    let mut proxy_log = String::new();
    for _ in 0..50 {
        proxy_log = read_file(journey.proxy.log_path());
        if proxy_log.contains("redaction telemetry report failed") {
            break;
        }
        tokio::time::sleep(Duration::from_millis(50)).await;
    }
    assert!(
        proxy_log.contains("redaction telemetry report failed"),
        "proxy log must record the failed best-effort telemetry report — without this, the \
         zero-alert state at the API is unmeasured, not a demonstrated clean pass; log was:\n{proxy_log}"
    );
    journey.canary.assert_absent("proxy log file", &proxy_log);
}

#[tokio::test(flavor = "multi_thread")]
async fn alert_only_forwards_the_canary_and_produces_no_alert() {
    // Negative control (AAASM-5877): same harness, opposite credential
    // action. If this test failed to see the RAW canary reach upstream, or
    // saw a dashboard alert appear, it would mean test 1's "redaction
    // worked" and "an alert appeared" assertions are true regardless of what
    // the proxy actually did — i.e. vacuous.
    let journey = spawn_journey("alert_only", None).await.expect("journey harness starts");

    let body = format!(
        r#"{{"model":"claude-sonnet-4-5","messages":[{{"role":"user","content":"my key is {}"}}]}}"#,
        journey.canary.value()
    );
    send_through_proxy(
        journey.proxy.addr().parse().expect("proxy addr is a socket address"),
        std::sync::Arc::new(
            client_trust_proxy_ca(journey.tmp.path().join("ca").as_path())
                .await
                .expect("client trusts proxy ca"),
        ),
        &body,
    )
    .await
    .expect("request through proxy");

    journey.upstream.wait_for_requests(1, Duration::from_secs(5)).await;
    let forwarded_body = journey.upstream.last_body().expect("upstream captured a body");
    assert!(
        forwarded_body.contains(journey.canary.value()),
        "alert_only must forward the ORIGINAL body unredacted — the opposite of test 1 \
         (this is what proves test 1's redaction assertion means something); got: {forwarded_body}"
    );

    // No dashboard alert: emit_redaction_telemetry only fires on the
    // ForwardedRedacted decision, not AlertAndForward (aa-proxy/src/proxy/mod.rs).
    let poll = wait_for_secret_alert(&journey.api, Duration::from_secs(3)).await;
    // See the equivalent note in the unreachable-telemetry test: a server
    // that was never actually reached is not evidence of "no alert".
    assert!(
        poll.observed,
        "the live aa-api-server was never successfully reached — cannot conclude 'no alert \
         reached it' from a server that was never actually asked; api log:\n{}",
        journey.api.logs(),
    );
    let has_secret = poll.json["items"]
        .as_array()
        .map(|items| items.iter().any(|a| a["category"] == "secret_detected"))
        .unwrap_or(false);
    assert!(
        !has_secret,
        "alert_only must not produce a dashboard secret_detected alert (the opposite of test 1); \
         got: {}",
        poll.json
    );
}

// =============================================================================
// External fixture: long-running process that boots the real out-of-process
// chain, drives one real canary request through it so an alert already
// exists, and idles. Invoked by AAASM-5904's Playwright globalSetup to give
// the browser spec a live dashboard-visible alert with nothing left to
// orchestrate — the spec only navigates and asserts.
// Marked `#[ignore]` so `cargo nextest run` skips it by default.
//
// AAASM-5908 (the api-server's unconditional ~30s self-terminate this
// fixture's original independent review flagged as a blocking gap) is now
// fixed, so this fixture's up-to-an-hour idle wait is no longer bounded by
// that defect.
// =============================================================================

#[tokio::test(flavor = "multi_thread")]
#[ignore = "long-running fixture spawned by AAASM-5904's Playwright globalSetup; idles until killed"]
async fn e2e_fixture_main() {
    use std::io::Write;

    let journey = spawn_journey("redact_only", None)
        .await
        .expect("fixture: journey harness should start");

    // Same request test 1 sends: a synthetic canary in an outbound LLM
    // payload, through the real proxy. Sent here (not left to the browser
    // spec) so the AC's "all orchestration stays in Rust" holds — by the
    // time READY prints, the dashboard's Alerts view has something to show.
    let body = format!(
        r#"{{"model":"claude-sonnet-4-5","messages":[{{"role":"user","content":"my key is {}"}}]}}"#,
        journey.canary.value()
    );
    let status = send_through_proxy(
        journey.proxy.addr().parse().expect("proxy addr is a socket address"),
        std::sync::Arc::new(
            client_trust_proxy_ca(journey.tmp.path().join("ca").as_path())
                .await
                .expect("client trusts proxy ca"),
        ),
        &body,
    )
    .await
    .expect("request through proxy");
    assert!(status.contains("200"), "CONNECT must succeed, got: {status}");

    // Confirm the alert actually landed before handing control to the
    // browser spec — a fixture that prints READY before the seed alert
    // exists would make the spec's own wait race the fixture instead of
    // testing the dashboard.
    let poll = wait_for_secret_alert(&journey.api, Duration::from_secs(10)).await;
    assert!(
        poll.observed
            && poll.json["items"]
                .as_array()
                .is_some_and(|items| items.iter().any(|a| a["category"] == "secret_detected")),
        "fixture: seed alert did not land on the live aa-api-server; api log:\n{}",
        journey.api.logs(),
    );

    // Single READY line on stdout, flushed immediately: the api-server's
    // REST base URL (what the dashboard's Playwright config proxies to),
    // the proxy's own address (unused by the current spec, kept for parity
    // with the harness's own request-through-proxy helper signature), and
    // the raw canary value itself — a synthetic, run-unique fake credential
    // ([`Canary`] docs), safe to print, that the Node-side spec needs
    // verbatim to assert its own *absence* from the rendered DOM and every
    // captured network response.
    println!(
        "READY {} {} {}",
        journey.api.base_url(),
        journey.proxy.addr(),
        journey.canary.value(),
    );
    std::io::stdout().flush().expect("flush stdout");

    // Idle until killed by the Playwright globalSetup teardown.
    loop {
        tokio::time::sleep(Duration::from_secs(3600)).await;
    }
}
