#!/usr/bin/env python3
"""Regenerate the shared mdBook metadata snippets under docs/src/generated/.

The core `agent-assembly` mdBook site references a small number of high-drift
values (workspace/runtime version, protocol version, canonical URLs, installer
command) from multiple pages. Before this generator those values were repeated
literally in each page, and had to be updated by hand on every release — the
exact drift pattern that AAASM-4310 exists to prevent.

This script is the single sanctioned writer for the ``docs/src/generated/``
directory. It reads:

* ``Cargo.toml`` — ``[workspace.package].version`` (the workspace runtime
  version; already the authoritative source for every crate in the workspace).
* ``metadata/docs.yaml`` — a small YAML file of docs-only values that are not
  encoded anywhere else in the tree (protocol version, canonical URLs,
  installer endpoints).

It writes one Markdown snippet per shared value under ``docs/src/generated/``.
Each snippet has a ``<!-- Generated by … — DO NOT EDIT. -->`` header so a
future maintainer editing the file directly is warned immediately.

Docs pages consume the snippets with mdBook's built-in include syntax::

    The latest tag is a pre-release ({{#include generated/version-tag.md}}).

Because the snippets are checked in, CI does not need Python or PyYAML to
*build* the docs — it only needs them to *verify* that the checked-in
snippets are up to date with their sources. The docs workflow runs::

    python3 scripts/generate_docs_metadata.py
    git diff --exit-code

If a human edits ``Cargo.toml`` or ``metadata/docs.yaml`` without re-running
the generator, ``git diff`` is non-empty and CI fails with an actionable
message.

The generator uses only the Python 3.11+ standard library (``tomllib`` for
Cargo.toml, a tiny hand-rolled parser for the flat scalar-only ``docs.yaml``
schema — sufficient for our fixed set of top-level keys and avoids pulling
PyYAML into CI). Adding new keys to ``docs.yaml`` is safe as long as they
remain single-line strings.

Refs: AAASM-4310.
"""

from __future__ import annotations

import sys
import tomllib
from pathlib import Path

# Snippets are anchored on the repository root: this script must remain at
# ``scripts/generate_docs_metadata.py`` and its parent's parent is the repo
# root. Resolving via ``__file__`` makes the generator invariant to the
# caller's working directory (CI, pre-commit, developer shell all work).
REPO_ROOT = Path(__file__).resolve().parent.parent
CARGO_TOML = REPO_ROOT / "Cargo.toml"
METADATA_YAML = REPO_ROOT / "metadata" / "docs.yaml"
GENERATED_DIR = REPO_ROOT / "docs" / "src" / "generated"

# Every generated snippet starts with this exact banner. Keeping it identical
# across files lets ``git grep`` locate every generated artefact and lets a
# future maintainer instantly recognise a file they must not edit.
HEADER = "<!-- Generated by scripts/generate_docs_metadata.py — DO NOT EDIT. -->"


def load_workspace_version() -> str:
    """Return the ``[workspace.package].version`` string from Cargo.toml.

    Failing loudly here is intentional: if the workspace version cannot be
    read we would rather stop the release than silently regenerate stale
    docs. ``tomllib`` is stdlib on Python 3.11+.
    """
    with CARGO_TOML.open("rb") as handle:
        data = tomllib.load(handle)
    try:
        return data["workspace"]["package"]["version"]
    except KeyError as exc:  # pragma: no cover - structural invariant
        raise SystemExit(
            f"Cargo.toml is missing [workspace.package].version (key path: {exc})."
        ) from exc


def load_docs_metadata() -> dict[str, str]:
    """Read ``metadata/docs.yaml`` into a flat ``{key: value}`` mapping.

    We deliberately do NOT depend on PyYAML: docs CI would then need it too,
    and the file is a tiny fixed-shape scalar map with no nesting, lists, or
    quoting quirks. The parser accepts::

        key: "value"      # double-quoted string
        key: 'value'      # single-quoted string
        key: value        # bare string
        # comment or blank line

    and rejects anything else with a clear error. Adding a new value to
    ``docs.yaml`` is safe as long as it fits this shape.
    """
    if not METADATA_YAML.is_file():
        raise SystemExit(f"metadata file not found: {METADATA_YAML}")

    result: dict[str, str] = {}
    for lineno, raw_line in enumerate(METADATA_YAML.read_text().splitlines(), start=1):
        line = raw_line.split("#", 1)[0].rstrip()
        if not line.strip():
            continue
        if ":" not in line:
            raise SystemExit(
                f"{METADATA_YAML}:{lineno}: expected 'key: value' — got: {raw_line!r}"
            )
        key, value = line.split(":", 1)
        key = key.strip()
        value = value.strip()
        if (value.startswith('"') and value.endswith('"')) or (
            value.startswith("'") and value.endswith("'")
        ):
            value = value[1:-1]
        if not key or not value:
            raise SystemExit(
                f"{METADATA_YAML}:{lineno}: empty key or value in: {raw_line!r}"
            )
        result[key] = value
    return result


def write_snippet(name: str, body: str) -> Path:
    """Write ``docs/src/generated/<name>`` with the standard header + body.

    The snippet contains no trailing newline after the body so that inline
    include contexts like ``pre-release ({{#include generated/version-tag.md}})``
    render as ``pre-release (v0.0.1-rc.3)`` without an unwanted line break.
    Header + body are separated by a single newline; git treats the file as
    a normal text file.
    """
    GENERATED_DIR.mkdir(parents=True, exist_ok=True)
    path = GENERATED_DIR / name
    path.write_text(f"{HEADER}\n{body}")
    return path


def main() -> int:
    workspace_version = load_workspace_version()
    docs_meta = load_docs_metadata()

    required = (
        "protocol_version",
        "repo_url",
        "docs_url",
        "install_script_url",
    )
    missing = [key for key in required if key not in docs_meta]
    if missing:
        raise SystemExit(
            f"{METADATA_YAML}: missing required key(s): {', '.join(missing)}"
        )

    # Bare workspace version, e.g. `0.0.1-rc.3`. Used where the docs render
    # a plain version number (aasm --version sample output style).
    write_snippet("version.md", workspace_version)

    # Tag-form version, e.g. `v0.0.1-rc.3`. Used where the docs render a
    # GitHub release tag (release-notes reference, latest-tag callouts).
    write_snippet("version-tag.md", f"v{workspace_version}")

    # Protocol version identifier, e.g. `protocol/v1`. Owned by
    # metadata/docs.yaml because the protocol version does not track the
    # workspace version 1:1 (pre-stable: protocol/v1 spans every v0.0.1 tag).
    write_snippet("protocol-version.md", docs_meta["protocol_version"])

    # Canonical URLs, emitted as bare strings so they compose in either
    # link-target position (`[text](…)`) or inline text position.
    write_snippet("repo-url.md", docs_meta["repo_url"])
    write_snippet("docs-url.md", docs_meta["docs_url"])

    # One-line installer command block. Kept as a full fenced code block so
    # pages consuming it don't have to open a fence themselves — dropping the
    # snippet in as a standalone include renders as a copy/paste-ready snippet.
    install_block = (
        "```sh\n"
        f"curl -sSf {docs_meta['install_script_url']} | sh\n"
        "```\n"
    )
    write_snippet("install.md", install_block)

    return 0


if __name__ == "__main__":
    sys.exit(main())
