import type { CapabilityAgent, CapabilityMatrix, Policy, Resource, SampleCall } from './types'

export const RESOURCES: Resource[] = [
  { id: 'gmail', name: 'Gmail', group: 'comm', paths: ['gmail/*', 'gmail/labels/INBOX/*', 'gmail/labels/INBOX/read', 'gmail/send'] },
  { id: 'gdrive', name: 'Google Drive', group: 'files', paths: ['gdrive/*', 'gdrive/shared/*', 'gdrive/personal/*'] },
  { id: 's3', name: 'AWS S3', group: 'files', paths: ['s3://*', 's3://reports/*', 's3://customer-pii/*'] },
  { id: 'pg', name: 'Postgres', group: 'data', paths: ['pg.public.*', 'pg.public.users', 'pg.public.orders', 'pg.public.audit_log'] },
  { id: 'shell', name: 'Shell exec', group: 'infra', paths: ['shell:*'] },
  { id: 'http', name: 'HTTP egress', group: 'infra', paths: ['http://*', 'https://*'] },
  { id: 'github', name: 'GitHub', group: 'code', paths: ['github.com/acme/*', 'github.com/acme/infra/*'] },
  { id: 'slack', name: 'Slack', group: 'comm', paths: ['slack/channels/*', 'slack/dm/*'] },
]

export const AGENTS: CapabilityAgent[] = [
  {
    id: 'research-bot-04',
    name: 'research-bot-04',
    framework: 'LangChain',
    owner: 'data-platform',
    trust: 42,
    mode: 'enforce',
    status: 'active',
    lastSeen: '2m ago',
    flagged: true,
    note: 'over-permissioned · 6 resources still allow, 4 narrowed, 0 deny',
    caps: {
      gmail: { read: 'allow', write: 'allow', delete: 'allow', exec: 'na', flag: true },
      gdrive: { read: 'allow', write: 'narrow', delete: 'allow', exec: 'na', flag: true },
      s3: { read: 'allow', write: 'allow', delete: 'approval', exec: 'na', flag: true },
      pg: { read: 'allow', write: 'approval', delete: 'deny', exec: 'na' },
      shell: { read: 'na', write: 'na', delete: 'na', exec: 'allow', flag: true },
      http: { read: 'allow', write: 'allow', delete: 'na', exec: 'na', flag: true },
      github: { read: 'allow', write: 'narrow', delete: 'deny', exec: 'na' },
      slack: { read: 'allow', write: 'narrow', delete: 'na', exec: 'na' },
    },
  },
  {
    id: 'support-triage',
    name: 'support-triage',
    framework: 'CrewAI',
    owner: 'cx-tools',
    trust: 78,
    mode: 'enforce',
    status: 'active',
    lastSeen: '12s ago',
    caps: {
      gmail: { read: 'allow', write: 'narrow', delete: 'deny', exec: 'na' },
      gdrive: { read: 'narrow', write: 'deny', delete: 'deny', exec: 'na' },
      s3: { read: 'narrow', write: 'deny', delete: 'deny', exec: 'na' },
      pg: { read: 'narrow', write: 'approval', delete: 'deny', exec: 'na' },
      shell: { read: 'na', write: 'na', delete: 'na', exec: 'deny' },
      http: { read: 'narrow', write: 'narrow', delete: 'na', exec: 'na' },
      github: { read: 'narrow', write: 'deny', delete: 'deny', exec: 'na' },
      slack: { read: 'allow', write: 'narrow', delete: 'na', exec: 'na' },
    },
  },
  {
    id: 'infra-ops-bot',
    name: 'infra-ops-bot',
    framework: 'AutoGen',
    owner: 'platform',
    trust: 88,
    mode: 'enforce',
    status: 'active',
    lastSeen: '1m ago',
    caps: {
      gmail: { read: 'deny', write: 'deny', delete: 'deny', exec: 'na' },
      gdrive: { read: 'deny', write: 'deny', delete: 'deny', exec: 'na' },
      s3: { read: 'narrow', write: 'narrow', delete: 'approval', exec: 'na' },
      pg: { read: 'narrow', write: 'narrow', delete: 'approval', exec: 'na' },
      shell: { read: 'na', write: 'na', delete: 'na', exec: 'narrow' },
      http: { read: 'allow', write: 'narrow', delete: 'na', exec: 'na' },
      github: { read: 'allow', write: 'narrow', delete: 'approval', exec: 'na' },
      slack: { read: 'narrow', write: 'approval', delete: 'na', exec: 'na' },
    },
  },
  {
    id: 'analytics-runner',
    name: 'analytics-runner',
    framework: 'LangChain',
    owner: 'analytics',
    trust: 71,
    mode: 'enforce',
    status: 'active',
    lastSeen: '4s ago',
    caps: {
      gmail: { read: 'deny', write: 'deny', delete: 'deny', exec: 'na' },
      gdrive: { read: 'narrow', write: 'deny', delete: 'deny', exec: 'na' },
      s3: { read: 'allow', write: 'narrow', delete: 'deny', exec: 'na' },
      pg: { read: 'allow', write: 'narrow', delete: 'deny', exec: 'na' },
      shell: { read: 'na', write: 'na', delete: 'na', exec: 'deny' },
      http: { read: 'narrow', write: 'deny', delete: 'na', exec: 'na' },
      github: { read: 'narrow', write: 'deny', delete: 'deny', exec: 'na' },
      slack: { read: 'narrow', write: 'deny', delete: 'na', exec: 'na' },
    },
  },
  {
    id: 'sales-outreach-v2',
    name: 'sales-outreach-v2',
    framework: 'LangGraph',
    owner: 'rev-ops',
    trust: 64,
    mode: 'shadow',
    status: 'active',
    lastSeen: '20s ago',
    caps: {
      gmail: { read: 'allow', write: 'approval', delete: 'deny', exec: 'na' },
      gdrive: { read: 'narrow', write: 'narrow', delete: 'deny', exec: 'na' },
      s3: { read: 'narrow', write: 'deny', delete: 'deny', exec: 'na' },
      pg: { read: 'narrow', write: 'approval', delete: 'deny', exec: 'na' },
      shell: { read: 'na', write: 'na', delete: 'na', exec: 'deny' },
      http: { read: 'narrow', write: 'narrow', delete: 'na', exec: 'na' },
      github: { read: 'deny', write: 'deny', delete: 'deny', exec: 'na' },
      slack: { read: 'allow', write: 'narrow', delete: 'na', exec: 'na' },
    },
  },
  {
    id: 'docs-summarizer',
    name: 'docs-summarizer',
    framework: 'LlamaIndex',
    owner: 'knowledge',
    trust: 92,
    mode: 'enforce',
    status: 'active',
    lastSeen: '8s ago',
    caps: {
      gmail: { read: 'narrow', write: 'deny', delete: 'deny', exec: 'na' },
      gdrive: { read: 'allow', write: 'deny', delete: 'deny', exec: 'na' },
      s3: { read: 'narrow', write: 'deny', delete: 'deny', exec: 'na' },
      pg: { read: 'narrow', write: 'deny', delete: 'deny', exec: 'na' },
      shell: { read: 'na', write: 'na', delete: 'na', exec: 'deny' },
      http: { read: 'narrow', write: 'deny', delete: 'na', exec: 'na' },
      github: { read: 'narrow', write: 'deny', delete: 'deny', exec: 'na' },
      slack: { read: 'deny', write: 'deny', delete: 'na', exec: 'na' },
    },
  },
  {
    id: 'incident-responder',
    name: 'incident-responder',
    framework: 'AutoGen',
    owner: 'sre',
    trust: 81,
    mode: 'enforce',
    status: 'active',
    lastSeen: '5m ago',
    caps: {
      gmail: { read: 'narrow', write: 'deny', delete: 'deny', exec: 'na' },
      gdrive: { read: 'narrow', write: 'deny', delete: 'deny', exec: 'na' },
      s3: { read: 'narrow', write: 'narrow', delete: 'deny', exec: 'na' },
      pg: { read: 'narrow', write: 'approval', delete: 'deny', exec: 'na' },
      shell: { read: 'na', write: 'na', delete: 'na', exec: 'narrow' },
      http: { read: 'allow', write: 'narrow', delete: 'na', exec: 'na' },
      github: { read: 'allow', write: 'narrow', delete: 'deny', exec: 'na' },
      slack: { read: 'allow', write: 'narrow', delete: 'na', exec: 'na' },
    },
  },
  {
    id: 'finance-bot',
    name: 'finance-bot',
    framework: 'CrewAI',
    owner: 'finance',
    trust: 55,
    mode: 'enforce',
    status: 'suspended',
    lastSeen: '2h ago',
    flagged: true,
    note: 'suspended after attempted cross-org S3 access',
    caps: {
      gmail: { read: 'narrow', write: 'deny', delete: 'deny', exec: 'na' },
      gdrive: { read: 'narrow', write: 'deny', delete: 'deny', exec: 'na' },
      s3: { read: 'deny', write: 'deny', delete: 'deny', exec: 'na', flag: true },
      pg: { read: 'narrow', write: 'approval', delete: 'deny', exec: 'na' },
      shell: { read: 'na', write: 'na', delete: 'na', exec: 'deny' },
      http: { read: 'narrow', write: 'deny', delete: 'na', exec: 'na' },
      github: { read: 'deny', write: 'deny', delete: 'deny', exec: 'na' },
      slack: { read: 'narrow', write: 'deny', delete: 'na', exec: 'na' },
    },
  },
]

export const POLICIES: Policy[] = [
  {
    id: 'P-014',
    name: 'PII-bearing tables require approval',
    scope: 'pg.public.users, pg.public.orders',
    status: 'active',
    version: 'v3.4.1',
    hits24h: 142,
    affects: ['research-bot-04', 'support-triage', 'sales-outreach-v2', 'docs-summarizer'],
    rules: [{ resource: 'pg', verb: ['write', 'delete'], action: 'approval', condition: 'table contains PII columns' }],
  },
  {
    id: 'P-021',
    name: 'No outbound email without scrub',
    scope: 'gmail/send · all agents',
    status: 'active',
    version: 'v3.4.1',
    hits24h: 89,
    affects: ['research-bot-04', 'support-triage', 'sales-outreach-v2'],
    rules: [
      { resource: 'gmail', verb: ['write'], action: 'scrub-then-allow', condition: 'always' },
      { resource: 'gmail', verb: ['write'], action: 'approval', condition: 'recipient not in @acme.com' },
    ],
  },
  {
    id: 'P-035',
    name: 'Customer-PII bucket lockdown',
    scope: 's3://customer-pii/*',
    status: 'active',
    version: 'v3.3.0',
    hits24h: 7,
    affects: ['research-bot-04', 'analytics-runner', 'finance-bot'],
    rules: [{ resource: 's3', verb: ['read', 'write', 'delete'], action: 'approval', condition: 'path matches customer-pii/*' }],
  },
  {
    id: 'P-042',
    name: 'Shell exec — break-glass only',
    scope: 'shell:* · all agents',
    status: 'active',
    version: 'v3.4.1',
    hits24h: 4,
    affects: ['research-bot-04', 'infra-ops-bot', 'incident-responder'],
    rules: [{ resource: 'shell', verb: ['exec'], action: 'approval', condition: 'always · 2-person review' }],
  },
  {
    id: 'P-058',
    name: 'GitHub write to infra repo · approval',
    scope: 'github.com/acme/infra/*',
    status: 'active',
    version: 'v3.4.1',
    hits24h: 12,
    affects: ['infra-ops-bot', 'incident-responder'],
    rules: [{ resource: 'github', verb: ['write'], action: 'approval', condition: 'repo matches acme/infra/*' }],
  },
  {
    id: 'P-066',
    name: 'proposed: research-bot-04 narrowing',
    scope: 'agent: research-bot-04',
    status: 'proposed',
    version: 'draft',
    hits24h: 0,
    affects: ['research-bot-04'],
    rules: [
      { resource: 'gmail', verb: ['write', 'delete'], action: 'deny', condition: 'always' },
      { resource: 's3', verb: ['write'], action: 'narrow', condition: 'path in [s3://reports/*]' },
      { resource: 'http', verb: ['write'], action: 'narrow', condition: 'host in allowlist' },
      { resource: 'shell', verb: ['exec'], action: 'deny', condition: 'always' },
    ],
  },
]

export const SAMPLE_CALLS: SampleCall[] = [
  { ts: '14:02:11', agent: 'research-bot-04', verb: 'write', resource: 'gmail/send', detail: 'to: ext@vendor.com', currentDecision: 'allow', proposedDecision: 'deny', changeType: 'newly-blocked' },
  { ts: '14:01:47', agent: 'research-bot-04', verb: 'exec', resource: 'shell:rm -rf /tmp/*', detail: 'shell command', currentDecision: 'allow', proposedDecision: 'deny', changeType: 'newly-blocked' },
  { ts: '13:58:22', agent: 'research-bot-04', verb: 'write', resource: 's3://reports/q3.csv', detail: 'CSV upload, 4MB', currentDecision: 'allow', proposedDecision: 'narrow', changeType: 'narrowed' },
  { ts: '13:54:09', agent: 'research-bot-04', verb: 'read', resource: 'gdrive/personal/*', detail: 'list files', currentDecision: 'allow', proposedDecision: 'allow', changeType: 'unchanged' },
  { ts: '13:51:33', agent: 'research-bot-04', verb: 'write', resource: 'http://api.foo.io/log', detail: 'POST 2KB', currentDecision: 'allow', proposedDecision: 'narrow', changeType: 'narrowed' },
  { ts: '13:48:10', agent: 'research-bot-04', verb: 'delete', resource: 'gmail/labels/INBOX/msg-9941', detail: 'delete email', currentDecision: 'allow', proposedDecision: 'deny', changeType: 'newly-blocked' },
  { ts: '13:35:44', agent: 'research-bot-04', verb: 'read', resource: 'pg.public.orders', detail: 'SELECT count(*)', currentDecision: 'allow', proposedDecision: 'allow', changeType: 'unchanged' },
  { ts: '13:31:02', agent: 'research-bot-04', verb: 'write', resource: 's3://customer-pii/seg.csv', detail: 'attempted upload', currentDecision: 'approval', proposedDecision: 'deny', changeType: 'tightened' },
]

export const CAPABILITY_MATRIX_FIXTURE: CapabilityMatrix = {
  resources: RESOURCES,
  agents: AGENTS,
  policies: POLICIES,
  sampleCalls: SAMPLE_CALLS,
}
